meta_product_name: "GemFinder"
meta_title: "GemFinder - Find Undervalued Property in London"
meta_description: "GemFinder aims to find undervalued property in London by analysing market trends and comparing list prices against historical sales."
meta_image: "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1200&h=630"
twitter_account: "@product_twitter_account"
